# Generated by Django 2.2.3 on 2019-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorkie',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yorkie',
            name='gender',
            field=models.CharField(default='male', max_length=25),
        ),
    ]
