# Generated by Django 2.2.3 on 2019-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190909_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorkie',
            name='gender',
            field=models.CharField(max_length=25),
        ),
    ]
