# Generated by Django 2.2.3 on 2019-09-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190910_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Grooming date')),
                ('care', models.CharField(choices=[('C', 'Coat brushing'), ('T', 'Toothbrushing'), ('B', 'Bath time')], default='C', max_length=1)),
                ('yorkie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Yorkie')),
            ],
        ),
    ]
