# Generated by Django 2.2.3 on 2019-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190911_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorkie',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
